namespace Atlas
{
    public enum EaseType
    {
        LinearIn,
        LinearOut,
        LinearInOut,
        ExponentialIn,
        ExponentialOut,
        ExponentialInOut,
        QuadraticIn,
        QuadraticOut,
        QuadraticInOut,
        BounceIn,
        BounceOut,
        BounceInOut,
        BackIn,
        BackOut,
        BackInOut,
        CircularIn,
        CircularOut,
        CircularInOut,
        CubicIn,
        CubicOut,
        CubicInOut,
        ElasticIn,
        ElasticOut,
        ElasticInOut,
        QuarticIn,
        QuarticOut,
        QuarticInOut,
        QuinticIn,
        QuinticOut,
        QuinticInOut,
        SineIn,
        SineOut,
        SineInOut
    }
}